# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tts_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11tts_service.proto\x12\x03tts\"\x94\x01\n\x11SynthesizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nspeaker_id\x18\x02 \x01(\x05\x12\x15\n\rpitch_control\x18\x03 \x01(\x02\x12\x16\n\x0e\x65nergy_control\x18\x04 \x01(\x02\x12\x18\n\x10\x64uration_control\x18\x05 \x01(\x02\x12\x14\n\x0c\x61udio_format\x18\x06 \x01(\t\"e\n\x12SynthesizeResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x14\n\x0c\x61udio_format\x18\x03 \x01(\t\x12\x10\n\x08\x64uration\x18\x04 \x01(\x02\"D\n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08sequence\x18\x02 \x01(\x05\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x32\x8a\x01\n\nTTSService\x12=\n\nSynthesize\x12\x16.tts.SynthesizeRequest\x1a\x17.tts.SynthesizeResponse\x12=\n\x10SynthesizeStream\x12\x16.tts.SynthesizeRequest\x1a\x0f.tts.AudioChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNTHESIZEREQUEST']._serialized_start=27
  _globals['_SYNTHESIZEREQUEST']._serialized_end=175
  _globals['_SYNTHESIZERESPONSE']._serialized_start=177
  _globals['_SYNTHESIZERESPONSE']._serialized_end=278
  _globals['_AUDIOCHUNK']._serialized_start=280
  _globals['_AUDIOCHUNK']._serialized_end=348
  _globals['_TTSSERVICE']._serialized_start=351
  _globals['_TTSSERVICE']._serialized_end=489
# @@protoc_insertion_point(module_scope)
